[project]
protostar-version = "0.10.0"
lib-path = "lib"
linked-libraries = ["zklink_starknet_contracts"]

[contracts]
zklink_starknet_contracts = ["zklink_starknet_contracts"]

[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321