[package]
name = "zklink"
version = "0.1.0"
description = "zklink starknet core contracts, cairo1.0 compatible"
homepage = "https://zk.link/"

[dependencies]
starknet = ">=2.1.0"
alexandria = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[cairo]
sierra-replace-ids = true

[scripts]
sierra = "cairo-compile . -r"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
# Enable CASM codegen.
casm = true
# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = false
# Enable allowed libfuncs validation.
allowed-libfuncs = true
allowed-libfuncs-list.name = "all"

[tool.snforge]