[package]
name = "zklink"
version = "0.1.0"
description = "zklink starknet core contracts, cairo1.0 compatible"
homepage = "https://zk.link/"

[dependencies]
starknet = ">=1.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test --starknet ."
build = "starknet-compile -c zklink::contracts::zklink::Zklink . ./target/dev/Zklink.json"

[[target.starknet-contract]]